### ISSUE TITLE
[linux/glibc] 5.7p1 compat secproctitle not working as expected

### ISSUE THREAD

**Issue by xtraeme** [openntpd-portable/openntpd-portable#1]
Platform is Linux with glibc, openntpd-5.7p1. Looks like compat_init_setproctitle() is not being called anywhere, and ntpd argv is not being overrided. At least this is my understanding of the compat code.

Additionally it's unlikely strnvis() will work without adding some more tests, the ones that openssh contains for SPT_TYPE.

**Comment by busterb** [comment]
Nice report @xtraeme , you are correct, I inadvertently dropped that patch from my queue.

I will fix it later and and look at syncing that compat code with OpenSSH's version. Cheers!

**Comment by xtraeme** [comment]
Thanks :+1:

**Comment by busterb** [comment]
Done. I removed strnvis encoding since it seemed like overkill for the 3 fixed C-locale strings that ntpd uses. Thanks for the report.
