### ISSUE TITLE
DNS malfunction results in permanent invalid host

### ISSUE THREAD

**Issue by leahneukirchen** [openntpd-portable/openntpd-portable#12]
When openntpd cannot resolve names of the server, it should retry doing this later (e.g. lack of connection on a notebook or something).

I noticed multiple times now this doesn't happen, and I'm stuck with "0/4 peers valid".

**Comment by bcook-r7** [comment]
Hi. Are you using the latest version openntpd-5.7p3? I believe that was an issue with p2 but it was resolved in the next release. If not, could you give info on your setup / OS?

**Comment by leahneukirchen** [comment]
It's openntpd-5.7p3_3 on Void Linux (kernel 3.18.7_1), no patches, started as "ntpd -d -s".

Possibly there was no network connection when ntpd started initially.

**Comment by busterb** [comment]
Thanks, for the info.

**Comment by busterb** [comment]
This appears to be an issue with the glibc implementation of getaddrinfo() and the interaction with how the network subsystem works on this OS. The resolver library appears to only read /etc/resolv.conf once. If a program performs a DNS lookup, then later /etc/resolv.conf is updated as the network comes up, it is never reread. We probably have to insert a periodic res_init() to get it to be read again. However, this is complicated because the DNS process runs in a chroot.

http://stackoverflow.com/questions/19930037/an-issue-of-getaddrinfo-function-call-on-linux-platform

**Comment by busterb** [comment]
Calling res_init before each call to getaddrinfo fixes it. sigh :)

In other words, ntpd is retrying, but the C library resolver has given up, and we need to keep encouraging it.

**Comment by busterb** [comment]
From what I can tell looking at my local Ubuntu 14.04 system, the glibc sources should be rereading resolv.conf when the timestamp changes in resolv/res_libc.c __res_maybe_init. Any idea why that might not be so on Void Linux? Maybe an issue with timestamps with BTRFS? I'm not necessarily seeing this problem on Ubuntu either, but its name resolution is quite a bit different. It uses a local caching DNS server, so /etc/resolv.conf always points to localhost.

**Comment by leahneukirchen** [comment]
a/c/mtime of /etc/resolv.conf certainly changes here... and plain ext4.  Sure, with a local DNS the contents of resolv.conf don't change really.

Good diagnosis. I'll watch ntpd reading from resolv.conf.

**Comment by leahneukirchen** [comment]
I don't run nscd either, btw.

**Comment by busterb** [comment]
Looking at strace for the DNS process, I see /etc/hosts being reread every time, but /etc/resolv.conf only once.

**Comment by busterb** [comment]
I tried a similar scenario with Ubuntu 14.04. The libc there does appear to reread /etc/resolv.conf if I updated it manually. I think you unfortunately have a bug in your system resolver. While we could maybe work around it with a manual res_init call, it is better fixed upstream. Do you agree?

**Comment by leahneukirchen** [comment]
upstream = glibc? Ok.

**Comment by busterb** [comment]
Right. Feel free to reopen if there's something we need to do on this end.
