### ISSUE TITLE
net-misc/openntpd-5.7_p4 : external qa issue

### ISSUE THREAD

**Issue by toralf** [openntpd-portable/openntpd-portable#16]
Hello,

a Gentoo Linux Quality Assurance issue was reported at my tinderbox [1] while building your software.

Such reported issues are often correct.
Otherwise it would be interesting why the issue is a false positive in your eyes.

[1] http://www.zwiebeltoralf.de/tinderbox/index.html
# 

QA: other
QA Notice: Package triggers severe warnings which indicate that it
           may exhibit random runtime failures.
imsg-buffer.c:258:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
Please do not file a Gentoo bug and instead report the above QA
issues directly to the upstream developers of this software.
Homepage: http://www.openntpd.org/

**Comment by busterb** [comment]
Thank you for the report. This issue should be resolved in the next release as of ee9bac45b93b30622cbe9e43e925ec7b91bda33a
