### ISSUE TITLE
It should be possible to disable HTTPS constraint at compilation time

### ISSUE THREAD

**Issue by lameventanas** [openntpd-portable/openntpd-portable#18]
Please add a --disable-https-constraint or similar to disable the HTTPS constraint code from ending up in the program.

I know it can be disabled through config file, but the code is still there and it makes it bigger, which is an issue in small devices.

**Comment by busterb** [comment]
Implemented in c6a2c11ecdadfffd43cda95112ac10485b7e5f73, thanks!
