### ISSUE TITLE
[linux/glibc] 5.7p1 does not listen/accept 

### ISSUE THREAD

**Issue by xtraeme** [openntpd-portable/openntpd-portable#2]
Somehow 5.7p1 is not listen()ing/accept()ing anything and that means that it won't accept connections to the ntp port. See the strace output of `ntpd -d` with `listen on *` enabled:

https://gist.github.com/anonymous/4650c0bcf6acf1470428

**Comment by busterb** [comment]
Hi @xtraeme , thanks for the report. Can you tell me what particular distribution you are using?

It seems to be working for me as expected with 'listen on *' using Ubuntu 14.04.

On the server side:
```
$ sudo ./ntpd -d -f ntpd.conf
listening on 127.0.0.1 
listening on 192.168.22.57 
```

On the client side (it takes a while for the server to sync):
```
sudo ./ntpd -d -f ntpd-client.conf 
ntp_adjtime adjusted frequency by 0.000000ppm
ntp engine ready
reply from 192.168.22.57: offset 0.000016 delay 0.000041, next query 6s 
reply from 192.168.22.57: offset 0.000052 delay 0.000145, next query 6s 
```

Keep in mind that OpenNTPD uses privilege separation, so the process that listens is not the main process. You may need to follow forks with strace.

**Comment by xtraeme** [comment]
http://www.voidlinux.eu

The distribution contains the latest and greatest, there's nothing special when building the binary package from sources, it's completely vanilla. Here's the source package:

https://github.com/voidlinux/void-packages/blob/master/srcpkgs/openntpd/template

The output was from `strace -f`.

The issue is that somehow it's not listening to the ntp udp port.

**Comment by busterb** [comment]
Interesring. 'lsof -p (second ntpd PID)' doesn't show the UDP listening sockets either?

**Comment by xtraeme** [comment]
http://www.enlightenment.org/ss/e-54b0091b4d7458.12709539.jpg

**Comment by busterb** [comment]
OK, I'll give voidlinux a try and see what it could be.

**Comment by xtraeme** [comment]
Hold on!

ntpd    1857 openntpd    6u  IPv4             102306      0t0     UDP localhost.localdomain:ntp 
ntpd    1857 openntpd    7u  IPv4             102307      0t0     UDP leysa.local:ntp 
ntpd    1857 openntpd    8u  IPv6             102308      0t0     UDP [::1]:ntp

**Comment by xtraeme** [comment]
Sorry, previous screenshot did not have "listen on *" enabled, this is the correct output:
```
COMMAND  PID     USER   FD   TYPE             DEVICE SIZE/OFF    NODE NAME
ntpd    1857 openntpd  cwd    DIR                8,3     4096 6689942 /var/empty
ntpd    1857 openntpd  rtd    DIR                8,3     4096 6689942 /var/empty
ntpd    1857 openntpd  txt    REG                8,3    70864 1319399 /usr/sbin/ntpd
ntpd    1857 openntpd  mem    REG                8,3    51896 1324159 /usr/lib/libnss_files-2.20.so
ntpd    1857 openntpd  mem    REG                8,3  1706232 1324162 /usr/lib/libc-2.20.so
ntpd    1857 openntpd  mem    REG                8,3  1965336 1324233 /usr/lib/libcrypto.so.30.0.3
ntpd    1857 openntpd  mem    REG                8,3   144952 1324161 /usr/lib/ld-2.20.so
ntpd    1857 openntpd    0w   CHR                5,1      0t0    1037 /dev/console
ntpd    1857 openntpd    1w   CHR                5,1      0t0    1037 /dev/console
ntpd    1857 openntpd    2w  FIFO                0,8      0t0    8741 pipe
ntpd    1857 openntpd    3u  unix 0xffff8802512f4000      0t0  102303 type=STREAM
ntpd    1857 openntpd    4u  unix 0xffff8803018ae300      0t0  103982 type=STREAM
ntpd    1857 openntpd    5u  unix 0xffff8803018aca80      0t0  103983 /var/run/ntpd.sock type=STREAM
ntpd    1857 openntpd    6u  IPv4             102306      0t0     UDP localhost.localdomain:ntp 
ntpd    1857 openntpd    7u  IPv4             102307      0t0     UDP leysa.local:ntp 
ntpd    1857 openntpd    8u  IPv6             102308      0t0     UDP [::1]:ntp 
ntpd    1857 openntpd    9u  IPv6             102310      0t0     UDP [fe80::be5f:f4ff:fe38:ced3]:ntp 
ntpd    1857 openntpd   10u  IPv6             102312      0t0     UDP [fe80::dfff:d7c7:abb9:77c7]:ntp 
ntpd    1857 openntpd   11u  IPv4             102313      0t0     UDP leysa.local:40506->ns1.indaloweb.net:ntp 
ntpd    1857 openntpd   12u  IPv4             102314      0t0     UDP leysa.local:34004->dnscache-madrid.eu.verio.net:ntp 
```

**Comment by xtraeme** [comment]
The weird thing is that `ss -lu` (to show UDP sockets listening) output is empty. 

Also the strace log had that:

```
[pid  1940] access("/proc/net", R_OK)   = -1 ENOENT (No such file or directory)
```

I'd like to know if this could be the reason somehow.

**Comment by xtraeme** [comment]
This is `iproute2` fault, I can see the expected behaviour with `netstat`.

```
$ netstat -ulpn
....  
udp        0      0 192.168.1.100:123       0.0.0.0:*                           9568/ntpd           
udp        0      0 127.0.0.1:123           0.0.0.0:*                           9568/ntpd 
```

Sorry for the noise, this is working correctly. Thanks.

**Comment by busterb** [comment]
Whew! No problem, glad to help.
