### ISSUE TITLE
PID path on ubuntu 

### ISSUE THREAD

**Issue by jungle-boogie** [openntpd-portable/openntpd-portable#22]
Hello,

I'm installing openntpd from the git repo on a ubuntu-like machine with a config option of:
`./configure --prefix=/usr/sbin/`

I have it installed and it's running but I can't seem to use `ntpctl` because:

```
$ ntpctl -sa
ntpctl: connect: /usr/local/var/run/ntpd.sock: No such file or directory
```

Is there a way to have ntpctl look for the ntpd.sock at the actual place it resides, `/var/run/openntpd.pid`?

Or should I edit /etc/init.d/openntpd to the path ntpctl thinks it is.

`/etc/init.d/openntpd`:
`DAEMON_OPTS="${DAEMON_OPTS:-} -p /var/run/openntpd.pid"``

Thanks!

**Comment by busterb** [comment]
--prefix is the high-level prefix where all of the program is installed. A proper value would be '--prefix=/usr', not /usr/sbin.

Also, the pid file has nothing to do with the control socket. The control socket's location is hard-coded at compile time. If you want to modify that, use this flag:

```
  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
```

e.g.: `./configure --prefix=/usr --localstatedir=/var`

**Comment by jungle-boogie** [comment]
Okay, did that.
Config log has this:
`localstatedir='/var'`

As expected...

here's the process:
`/usr/sbin/ntpd -f /etc/openntpd/ntpd.conf -p /var/run/openntpd.pid`

```
% ntpctl -sa      
ntpctl: connect: /usr/local/var/run/ntpd.sock: No such file or directory
```

**Comment by busterb** [comment]
Dumb question, but did you run 'make clean' before reinstalling?

**Comment by jungle-boogie** [comment]
I did so a few times now and the results are the same:

```
$ ntpctl -sa
ntpctl: connect: /usr/local/var/run/ntpd.sock: No such file or directory
```

**Comment by busterb** [comment]
If you do 'make clean' followed by `make V=1`, do you see your path in the compiler output like so?

```
./configure --sysconfdir=/etc --localstatedir=/var/opentpd
...
-DSYSCONFDIR=\"/etc\"  -DLOCALSTATEDIR=\"/var/opentpd\" 
```

**Comment by jungle-boogie** [comment]
```
-DSYSCONFDIR=\"/usr/etc\
-DLOCALSTATEDIR=\"/var\
```

With this config string:
`./configure --prefix=/usr --localstatedir=/var`

**Comment by busterb** [comment]
Sorry, I just cannot reproduce the behavior you have reported on any current version. I'll put out a new tar release with the other current fixes and let me know how it works for you.

**Comment by jungle-boogie** [comment]
Hi @busterb,

No problem at all. Could you please show all commands you type to set it up in Ubuntu? I'll do the same and see what occurs. 

Thanks!

**Comment by busterb** [comment]
The commands that I used were simply the configure line above, followed by make; make install. Any changes with the latest release?

**Comment by busterb** [comment]
Going to close for now, since I haven't heard back in a while.
