### ISSUE TITLE
5.9p1 broken on RHEL 6 (and other older linux varients)

### ISSUE THREAD

**Issue by pbhenson** [openntpd-portable/openntpd-portable#23]
configure fails to find clock_gettime on RHEL 6:

```
configure:12343: checking for clock_gettime                                                                   
configure:12343: cc -std=gnu99 -o conftest   -Wno-pointer-sign -Wall -std=gnu99 -fno-strict-aliasing  -D_DEFAU
LT_SOURCE -D_BSD_SOURCE -D_POSIX_SOURCE -D_GNU_SOURCE -Wl,-R/usr/pkg/lib  conftest.c  >&5                     
/tmp/ccAEypp8.o: In function `main':                                                                          
conftest.c:(.text+0xa): undefined reference to `clock_gettime'                                                
collect2: ld returned 1 exit status                                                                           
```

However, the function does exist, but you need to link to librt to find it:

```
CLOCK_GETRES(2)            Linux Programmer’s Manual           CLOCK_GETRES(2

NAME                                                                         
       clock_getres, clock_gettime, clock_settime - clock and time functions 

SYNOPSIS                                                                     
       #include <time.h>                                                     

       int clock_getres(clockid_t clk_id, struct timespec *res);             

       int clock_gettime(clockid_t clk_id, struct timespec *tp);             

       int clock_settime(clockid_t clk_id, const struct timespec *tp);       

       Link with -lrt.                                                       

This results in a compile failure:

  CC       arc4random.lo                                                    
In file included from ../include/time.h:6,                                  
                 from /usr/include/pthread.h:26,                            
                 from arc4random_linux.h:28,                                
                 from arc4random.h:10,                                      
                 from arc4random.c:66:                                      
/usr/include/time.h:336: error: conflicting types for 'clock_gettime'       
../include/time.h:22: note: previous declaration of 'clock_gettime' was here
*** Error code 1                                                            
```

This is evidently only an issue on distributions with glibc older than 2.17.

Any thoughts on the best approach to resolving this?

**Comment by busterb** [comment]
Yeah, we have code designed to check for the -lrt dependency already, it just appears that autoconf is caching the wrong result before we do that check:

```
checking for clock_gettime... (cached) no
checking for clock_getres... yes
checking for library containing clock_getres... none required
checking for library containing clock_gettime... (cached) -lrt
```

Solution is to swap the order of the library and function checks so the library dependency is already added when we do the function check.

**Comment by pbhenson** [comment]
Hmm, why is it checking twice?

checking for clock_gettime... no
checking for library containing clock_gettime... -lrt
[...]
checking for clock_gettime... (cached) no
checking for clock_getres... yes
checking for library containing clock_getres... none required
checking for library containing clock_gettime... (cached) -lrt

I tried changing the order:

$ diff configure.ac.orig configure.ac
54,55d53
< AC_CHECK_FUNCS([adjfreq ntp_adjtime adjtimex])
< AC_CHECK_FUNCS([clock_gettime clock_getres])
57a56,57

> AC_CHECK_FUNCS([adjfreq ntp_adjtime adjtimex])
> AC_CHECK_FUNCS([clock_gettime clock_getres])

which didn't really seem to do anything in the resultant configure except move the tests around:

12646,12669d12645
< for ac_func in adjfreq ntp_adjtime adjtimex
< do :
<   as_ac_var=`$as_echo "ac_cv_func_$ac_func" | $as_tr_sh`
< ac_fn_c_check_func "$LINENO" "$ac_func" "$as_ac_var"
< if eval test \"x\$"$as_ac_var"\" = x"yes"; then :
<   cat >>confdefs.h <<_ACEOF
< #define `$as_echo "HAVE_$ac_func" | $as_tr_cpp`1
< _ACEOF
< 
< fi
< done
< 
< for ac_func in clock_gettime clock_getres
< do :
<   as_ac_var=`$as_echo "ac_cv_func_$ac_func" | $as_tr_sh`
< ac_fn_c_check_func "$LINENO" "$ac_func" "$as_ac_var"
< if eval test \"x\$"$as_ac_var"\" = x"yes"; then :
<   cat >>confdefs.h <<_ACEOF
< #define`$as_echo "HAVE_$ac_func" | $as_tr_cpp` 1
< _ACEOF
< 
< fi
< done
< 
12781a12758,12781

> for ac_func in adjfreq ntp_adjtime adjtimex
> do :
>   as_ac_var=`$as_echo "ac_cv_func_$ac_func" | $as_tr_sh`
> ac_fn_c_check_func "$LINENO" "$ac_func" "$as_ac_var"
> if eval test \"x\$"$as_ac_var"\" = x"yes"; then :
>   cat >>confdefs.h <<_ACEOF
> #define `$as_echo "HAVE_$ac_func" | $as_tr_cpp` 1
> _ACEOF
> 
> fi
> done
> 
> for ac_func in clock_gettime clock_getres
> do :
>   as_ac_var=`$as_echo "ac_cv_func_$ac_func" | $as_tr_sh`
> ac_fn_c_check_func "$LINENO" "$ac_func" "$as_ac_var"
> if eval test \"x\$"$as_ac_var"\" = x"yes"; then :
>   cat >>confdefs.h <<_ACEOF
> #define `$as_echo "HAVE_$ac_func" | $as_tr_cpp` 1
> _ACEOF
> 
> fi
> done

They still did the same thing:

checking for clock_gettime... no
checking for library containing clock_gettime... -lrt
[...]
checking for clock_gettime... (cached) no
checking for clock_getres... yes
checking for library containing clock_getres... none required
checking for library containing clock_gettime... (cached) -lrt

I even tried moved them up to by the libc library checks and the same result. My autoconf fu isn't that high. I'll wait for you to sort it out :), then patch 5.9p1 so I can bump pkgsrc.

Thanks...

**Comment by busterb** [comment]
no worries; I already have a patch, will check it in later. Hope to have a p2 release with a few more portable fixes.

**Comment by pbhenson** [comment]
Cool. Any idea on the p2 timeline yet? If it's relatively soon I might just wait for it rather than push out a patched p1 to pkgsrc. I already submitted p1 to gentoo, it has a recent glibc and I didn't run into this issue there.

Thanks...

**Comment by busterb** [comment]
I don't see any reason to hang onto it more than a couple of days more; I have some FreeBSD bugs I'd like to fix and this basically.

**Comment by pbhenson** [comment]
Hmm, well, haven't seen a new release cut and there don't seem to be any fresh commits, so I guess you've been busy with other stuff :). Ahh, always that other stuff ;). On the bright side 5.9p1 has been working great under Gentoo, Solaris, and OmniOS. I almost pushed the update into pkgsrc before I tested RHEL 6, guess I would have been trading Solaris 10 support for older Linux support if I had.

**Comment by busterb** [comment]
Hi @pbhenson, pushed the fix now; let me know if that does the trick for you before I look at pushing a p2.

**Comment by pbhenson** [comment]
Yup, looks good; compiles and runs fine on RHEL 6 now, thanks. The configure.ac change is the same as what I tried but I didn't know about the check-libc-compat.m4 stuff.
