### ISSUE TITLE
ntpd exec ignores specified privsep-user, fails @ "ntpd: unknown user _ntp"

### ISSUE THREAD

**Issue by ghost** [openntpd-portable/openntpd-portable#24]
Building openntpd 5.9p1 on opensuse/64,

```
useradd  openntpd -g openntpd -G "" -s /bin/false -d /var/run/openntpd -M
id openntpd
    uid=5502(openntpd) gid=5503(openntpd) groups=5503(openntpd)
ls -ald /var/run/openntpd
    drwxr-xr-x 2 openntpd openntpd 40 Apr 17 07:00 /var/run/openntpd/

cd  openntpd-5.9p1
```

with specified privsep user == 'openntpd', 

```
autoreconf -vif
./configure \
--prefix=/usr/local/openntpd \
--enable-shared --disable-static \
--with-privsep-user=openntpd \
--with-privsep-path=/var/run/openntpd \
--with-gnu-ld

make
make install

ls -al /usr/local/openntpd/sbin/ntpd
    -rwxr-xr-x 2 root root 126K Apr 17 07:26 /usr/local/openntpd/sbin/ntpd*
```

exec fails, complaining about missing '_ntp' user

```
/usr/local/openntpd/sbin/ntpd -v -d -s \
 -f /usr/local/etc/openntpd/openntpd.conf \
 -p /var/run/openntpd/openntpd.pid

ntpd: unknown user _ntp
```

**Comment by Obarun** [comment]
@pgnd , may be a workaround, try this before building it

`sed -i 's:"_ntp":"ntp":' src/ntpd.h`

**Comment by ghost** [comment]
@Obarun That results in 

```
 ntpd: unknown user ntp
```

The point is that it's, for whatever reason, ignoring the configure-time-specified privsep-user ...

Switching to latest git source,

```
commit 827fa346509332556f18bd45f7cb4854f2736e0b
```

appears to cure the problem, as I'm now able to launch as 'openntpd' user, with no further complaint.
I do not know -- yet -- they 'why' of it ...

**Comment by Obarun** [comment]
grr i'm an idiot, for you the line need to be : 
`sed -i 's:"_ntp":"openntpd":' src/ntpd.h`

**Comment by ghost** [comment]
That appears to work as a workaround.

Still begs the question as to why the config param's being ignored.

**Comment by busterb** [comment]
Hmm, I cannot reproduce locally. Why are you running 'autoreconf' on the released tarballs anyway? What version of openSuSE is this? If you want to debug some, try running `make clean; make V=1`.

You should see `-DNTPD_USER=\"openntpd\"` in the compiler output

**Comment by busterb** [comment]
It's been a while and I still can't see this happening. Main suggestion would be to use the release tarballs as-is without rerunning autoreconf.
