### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by sebcouf** [openntpd-portable/openntpd-portable#27]
Hi,
I m using OpenNtpd (6.0p1_1,2) on a FreeBSD OS (10.3-RELEASE-p9) installed with "pkg" pre compil  repository. Since last updates of the 3 dependencies (libssl.so.38,  libtls.so.10, libcrypto.so.37), i encounter a disfonctionement. I had to create symbolic links to the new versions of the libs (ex: libtls.so.10@ -> /usr/local/lib/libtls.so.11.0.0). There is natively an updated  symbolic link from  libtls.so@ to the latest version (even for libssl and lybcrypto), is it possible to compil a vesion of Openntpd point to theses links?
Sébastien

**Comment by busterb** [comment]
Please recompile openntpd whenever updating library versions. This is something you should note with the FreeBSD package maintainer instead. Thanks!
