### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by Obarun** [openntpd-portable/openntpd-portable#28]
Can you make a new release please for 6.1p1 version?
Many thanks

**Comment by busterb** [comment]
We're still a few months from OpenBSD 6.1 being released, though testing of what's here now would be greatly appreciated.

**Comment by spacekitteh** [comment]
@busterb maybe a 6.0p2 in the meantime?

**Comment by l2dy** [comment]
Any update? OpenBSD 6.1 was released on Apr 11, 2017.

**Comment by busterb** [comment]
master is updated, I'm going to close this and work on a new release based on that.
