### ISSUE TITLE
openntpd portable autogen/sh/update.sh FAILs; checkout missing openbsd/src/lib/libcrypto/crypto/getentropy_*.c

### ISSUE THREAD

**Issue by ghost** [openntpd-portable/openntpd-portable#30]
Attempting to build openntpd-portable branch 6_0 on linux64

    git clone https://github.com/openntpd-portable/openntpd-portable.git openntpd
    cd openntpd
    git checkout remotes/origin/OPENBSD_6_0
    git log | head
        commit 086d3b975398513184b914010ec47cfd4fea8bac
        Author: Brent Cook <bcook@openbsd.org>
        Date:   Sat Aug 13 14:24:26 2016 -0500

            point to OPENBSD_6_0

        commit 0cca9346f1333bceacce4920de4c44010f45b398
        Author: Brent Cook <bcook@openbsd.org>
        Date:   Mon May 30 17:49:49 2016 -0500

    cat INSTALL
        ...
        2. Building / Installation
        --------------------------

        If you have checked this source using Git, follow these initial steps to
        prepare the source tree for building:

         1. ensure you have the following packages installed:
              automake, autoconf, git, libtool
         2. run './autogen.sh' to prepare the source tree for building
            or run './dist.sh' to prepare a tarball.
        ...

    ./autogen.sh
        pulling upstream openbsd source
        Cloning into 'openbsd'...
        remote: Counting objects: 23061, done.
        remote: Total 23061 (delta 0), reused 0 (delta 0), pack-reused 23061
        Receiving objects: 100% (23061/23061), 4.12 MiB | 2.05 MiB/s, done.
        Resolving deltas: 100% (13543/13543), done.
        Checking connectivity... done.
        Branch OPENBSD_6_0 set up to track remote branch OPENBSD_6_0 from origin.
        Switched to a new branch 'OPENBSD_6_0'
        Current branch OPENBSD_6_0 is up to date.
        ./update.sh: line 55: /usr/local/src/openntpd/openbsd/src/lib/libcrypto/crypto/getentropy_*.c: No such file or directory

The update.sh script fails at missing file under libcrtypo/...

Doesn't appear that the update.sh script's checkout is complete

    ls /usr/local/src/openntpd/openbsd/src/lib/
        libc/  libutil/

Cref:

    https://github.com/openntpd-portable/openntpd-openbsd/tree/master/src/lib

**Comment by ghost** [comment]
fwiw, if I checkout master, instead of 6_0 branch, then the update.sh pull is complete, and the autogen.sh script completes ...

but, build of master branch fails, which is a different issue: https://github.com/openntpd-portable/openntpd-portable/issues/31

**Comment by akerl** [comment]
This appears to have been fixed in 6b32cedc37296d836d93f370923b8e0d2e8eee1b , but that's between 6.0p1 and HEAD

**Comment by ilyaevseev** [comment]
quick&dirty fix: https://github.com/ilyaevseev/fedora-spec/blob/master/openntpd/openntpd.spec#L46

**Comment by busterb** [comment]
Hmm, I forget exactly when the repo move happened, will see about backporting to that branch.

**Comment by busterb** [comment]
ahh, failure is due to not including both old and new paths in cvs->git converter, will fix that.

**Comment by busterb** [comment]
fixed the converter, thanks!
