### ISSUE TITLE
build error: "error: conflicting types for ‘priv_constraint_msg"

### ISSUE THREAD

**Issue by ghost** [openntpd-portable/openntpd-portable#31]
build of openntpd master

	git log | head
		commit ca8e7f797cb06e3b933ed250c9e7fc5d875d7de3
		Author: Brent Cook <bcook@openbsd.org>
		Date:   Thu Nov 10 11:43:48 2016 -0600

		    update patches, add missing : in getopt format

		commit 0d40f56662d029381fbaebf9871228d06a98b32c
		Author: Brent Cook <bcook@openbsd.org>
		Date:   Sat Nov 5 13:15:09 2016 -0500

	./autogen.sh
	./configure \
	--prefix=/usr/local/openntpd \
	--enable-shared --disable-static \
	--with-privsep-user=openntpd \
	--with-privsep-path=/var/empty-openntpd \
	--with-cacert=path=/etc/ssl/cert.pem \
	--disable-https-constraint \
	--with-gnu-ld
	make V=1 -j4

fails @ "constraint-disabled.c:46:1: error: conflicting types for ‘priv_constraint_msg’"

	...
	/usr/bin/gcc-6 -DPACKAGE_NAME=\"OpenNTPD\" -DPACKAGE_TARNAME=\"openntpd\" -DPACKAGE_VERSION=\"6.1p1\" -DPACKAGE_STRING=\"OpenNTPD\ 6.1p1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"openntpd\" -DVERSION=\"6.1p1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSPT_TYPE=SPT_REUSEARGV -DHAVE_GETAUXVAL=1 -DHAVE_ASPRINTF=1 -DHAVE_DAEMON=1 -DHAVE_MEMMEM=1 -DHAVE_POLL=1 -DHAVE_SETGROUPS=1 -DHAVE_SETREGID=1 -DHAVE_SETRESGID=1 -DHAVE_SETREUID=1 -DHAVE_SETRESUID=1 -DHAVE_SYSCONF=1 -DHAVE_NTP_ADJTIME=1 -DHAVE_ADJTIMEX=1 -DHAVE_CLOCK_GETTIME=1 -DHAVE_CLOCK_GETRES=1 -DHAVE___PROGNAME=1 -DHAVE_VA_COPY=1 -DHAVE___VA_COPY=1 -DHAVE_SYS_SYSCTL_H=1 -DHAVE_ERR_H=1 -DHAVE_IFADDRS_H=1 -DHAVE_PATHS_H=1 -DNTPD_USER=\"openntpd\" -DCONSTRAINT_CA=\"path=/etc/ssl/cert.pem\" -I.  -I../include -DYYSTYPE_IS_DECLARED -O3 -Wall -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fmessage-length=0 -grecord-gcc-switches -march=native -mtune=native -D_FORTIFY_SOURCE=2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_SOURCE -D_GNU_SOURCE -O3 -Wall -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fmessage-length=0 -grecord-gcc-switches -march=native -mtune=native  -Wno-pointer-sign -Wall -std=gnu99 -fno-strict-aliasing -DSYSCONFDIR=\"/usr/local/openntpd/etc\" -DLOCALSTATEDIR=\"/usr/local/openntpd/var\" -O3 -Wall -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fmessage-length=0 -grecord-gcc-switches -march=native -mtune=native  -Wno-pointer-sign -Wall -std=gnu99 -fno-strict-aliasing -MT ntpd-log.o -MD -MP -MF .deps/ntpd-log.Tpo -c -o ntpd-log.o `test -f 'log.c' || echo './'`log.c
	constraint-disabled.c:46:1: error: conflicting types for ‘priv_constraint_msg’
	 priv_constraint_msg(u_int32_t id, u_int8_t *data, size_t len,
	 ^~~~~~~~~~~~~~~~~~~
	In file included from constraint-disabled.c:19:0:
	ntpd.h:380:7: note: previous declaration of ‘priv_constraint_msg’ was here
	 void  priv_constraint_msg(u_int32_t, u_int8_t *, size_t, int, char **);
	       ^~~~~~~~~~~~~~~~~~~
	Makefile:569: recipe for target 'ntpd-constraint-disabled.o' failed
	make[1]: *** [ntpd-constraint-disabled.o] Error 1
	mv -f .deps/ntpd-config.Tpo .deps/ntpd-config.Po
	mv -f .deps/ntpd-log.Tpo .deps/ntpd-log.Po
	mv -f .deps/ntpd-client.Tpo .deps/ntpd-client.Po
	mv -f .deps/ntpd-control.Tpo .deps/ntpd-control.Po
	make[1]: Leaving directory '/usr/local/src/openntpd/src'
	Makefile:402: recipe for target 'all-recursive' failed
	make: *** [all-recursive] Error 1

**Comment by busterb** [comment]
Fixed in b11faba94aeeb195d98b71847e9f9768dd71eb04, thanks!
