### ISSUE TITLE
constraints disabled?

### ISSUE THREAD

**Issue by jungle-boogie** [openntpd-portable/openntpd-portable#33]
Hi All,

Just curious if there's a technical reason to have ntp.conf disable the constraints function:
https://github.com/openntpd-portable/openntpd-portable/blob/a7577667d673f49800e15461fe384817a1572eae/ntpd.conf#L21

**Comment by busterb** [comment]
Not really. I'll resync with the upstream ntp.conf

**Comment by busterb** [comment]
there are 2 ntpd.conf files in the openbsd tree to choose from - the one that gets installed by default, and the one that is included in the examples directory. I'll assume the former gets a lot more actual usage, so will mirror it.

**Comment by busterb** [comment]
I've updated master to use the same ntpd.conf that is installed by default with OpenBSD, enabling constraints by default.
