### ISSUE TITLE
ntpd is using deprecated sysctl system call

### ISSUE THREAD

**Issue by Spork-Schivago** [openntpd-portable/openntpd-portable#34]
Hi,

I love openntpd-portable.   I noticed something in dmesg though.   I see the following:

warning: process `ntpd' used the deprecated sysctl system call with 1.40.6.

It seems openntpd is using a deprecated syscall.

Is there a reason for this or should it be fixed?

The machine openntpd is running on is a CentOS 7 (Linux) server running kernel 4.8.6-x86_64.

Thanks!

**Comment by busterb** [comment]
It is using the sysctl call to get entropy from the system. Did you originally build the binaries on this system? It should be using getrandom with this kernel, but only if the syscall number is available in the kernel headers.

**Comment by Spork-Schivago** [comment]
Thank you for the quick reply.   I did build the binaries on the system it's running, and the kernel version has not changed.   It's running on a VPS.  It's running under KVM.  I wonder if that has anything to do with it.

A little more information.   CentOS 7 provides kernel version 3.10.0-514.2.2 right now.  But Linode does some fancy stuff and let me choose to between running the kernel that comes with CentOS, using their kernel, or custom compiling my own.   I chose to use their kernel, which is version 4.8.6, however, it's not actually installed on the system.   I'm not sure how they do it, but somehow my system boots off their kernel without their kernel actually being installed anywhere on the physical hard drive.

Do I need the kernel source code or do most distributions provide the headers with a default install?   Because I'm running a kernel version that CentOS 7 doesn't provide, will I need to download and install the 4.8.6 kernel headers?   Thanks!

**Comment by busterb** [comment]
You would need kernel headers >= 3.17 in order to build OpenNTPD with getrandom support, which then removes calls to sysctl. You should not need the full source.

**Comment by Spork-Schivago** [comment]
I gotcha.   The headers don't need to match the current kernel version?   They just need to be newer than 3.17?   Sorry for thinking this was a bug.   I should have looked through the source code (or maybe even the README, if it's in there).   I was following a how-to for CentOS 7 and it listed the various steps for compiling.   I should have still read through the various installation documents.

Thanks and sorry for this.   I appreciate you taking the time to explain everything to me.   I believe this ticket can now be closed.
