### ISSUE TITLE
clock remains in "unsynced" state, regardless of all-valid, or some-invalid peers

### ISSUE THREAD

**Issue by pacocc** [openntpd-portable/openntpd-portable#35]
Same issue as #25 which was closed but not fixed.  This is on a multi-cpu FreeBSD 11.0 system running 6.0p1. Clock can be accurate to <=1s pre-start, using "-s" or not, but peers are always listed as "not valid". Debugging indicates "no reply from ... received in time" despite tcpdump logging timely packets. FWIW, the identical configuration worked on the previous hardware which had a single cpu

**Comment by floand** [comment]
Saw the probably same behaviour here using OpenNTPD version 6.0_p1.

Description:
Clock stays mostly in unsynced state. Regularly after approximately 15 minutes state changed to “now synced” but only for around 3 minutes. Then this behaviour always repeats.

Resolved by:
Deleting _/var/lib/openntpd/ntpd.drift_ which contains a value of -523.839 and restarting ntpd service afterwards solved the described behaviour — at least for me. Maybe
    `echo '0.0' > /var/lib/openntpd/ntpd.drift`
will also work (not tested).

Hope that helps.

**Comment by pacocc** [comment]
Removing the drift file didn't have an effect on this server.
