### ISSUE TITLE
clock remains in "unsynced" state, regardless of all-valid, or some-invalid peers

### ISSUE THREAD

**Issue by pacocc** [openntpd-portable/openntpd-portable#38]
Same issue as #25 and #35 which were closed unfixed (how does that work?). This is on a multi-cpu FreeBSD 11.0 system running 6.0p1. Clock can be accurate to <=1s pre-start, using "-s" or not, but peers are always listed as "not valid". Debugging indicates "no reply from ... received in time" despite tcpdump logging timely packets. FWIW, the identical configuration worked on the previous hardware which had a single cpu

**Comment by busterb** [comment]
> (how does that work?)

Easy! One person has a problem with a specific setup (say, Solaris), then everyone piles on with different scenarios assuming its the same problem (in your case, multiple CPUs with FreeBSD). Thanks for opening a different issue, since it sounds like this needs a different fix.

Can you try master?

**Comment by pacocc** [comment]
Turns out to have been a source ip vs firewall issue.  Despite the "listen" address openntpd still sends queries out using the server's primary ip address.  There is apparently (still) no way to define the outgoing source ip in ntpd.conf.

**Comment by busterb** [comment]
that's something you need? probably pretty easy to implement
