### ISSUE TITLE
ntpd: socketpair: Protocol not supported on macOS

### ISSUE THREAD

**Issue by l2dy** [openntpd-portable/openntpd-portable#39]
On macOS 10.12 and 10.11, `sudo /opt/local/sbin/ntpd -d -v -f /opt/local/etc/ntpd.conf` exited immediately with `ntpd: socketpair: Protocol not supported`.

I tried openntpd 6.1p1, 6.2p1 and 6.2p2 built with MacPorts, all crashed.

Caused by openntpd-portable/openntpd-openbsd@52dfcba261e6e24571ca9651e1fc6b00c64dee50 using `SOCK_CLOEXEC` which is not supported on OS X.

**Comment by hdatma** [comment]
Just a note on passing. Although this issue was closed in early September, and a new version was released therein, the issue is still pending in real life. The mirrored version is still 6.2p2 instead of 6.2p3.
