### ISSUE TITLE
OpenNTPD won't install - Install via apt-get

### ISSUE THREAD

**Issue by DocDriven** [openntpd-portable/openntpd-portable#49]
Hello,

I have problems with installing OpenNTPD on my Ubuntu virtual machine. It is Ubuntu 14.04.4 LTS, which I updated and upgraded right before the install. But when invoking the install via `sudo apt-get install openntpd`, I receive a strange error (this is a German version of Ubuntu, but I changed the output to English):

cba@cba-VirtualBox:~$ LC_ALL=c sudo apt-get install openntpd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  openntpd
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/33.9 kB of archives.
After this operation, 184 kB of additional disk space will be used.
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "de_DE",
	LC_ALL = "c",
	LC_TIME = "en_US.UTF-8",
	LANG = "de_DE.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Selecting previously unselected package openntpd.
(Reading database ... 190167 files and directories currently installed.)
Preparing to unpack .../openntpd_20080406p-7_amd64.deb ...
Unpacking openntpd (20080406p-7) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up openntpd (20080406p-7) ...
**_Starting openntpd: /etc/openntpd/ntpd.conf: Permission denied
invoke-rc.d: initscript openntpd, action "start" failed.
dpkg: error processing package openntpd (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for ureadahead (0.100.0-16) ...
E: Sub-process /usr/bin/dpkg returned an error code (1)_**

I've marked the part when the install fails. The ntpd.conf file did not exist pre-installing. Therefore, I couldn't change the permissions accidentally.

Has anybody experienced this kind of problem? I was unable to find a solution on the internet.

Thanks in advance!

Regards,

**Comment by busterb** [comment]
I couldn't help you much here. Check to make sure your filesystem is actually mounted read-write rather than read-only.
