### ISSUE TITLE
Duplicate definitions of `ibuf_dns` and `conf`

### ISSUE THREAD

**Issue by michaelforney** [openntpd-portable/openntpd-portable#57]
Not sure if this is the right place to report this issue, since while it is a portability issue, it probably should be fixed upstream in OpenBSD.

The `conf` variable is declared as `extern` in `src/ntpd.h`, but is defined in both `src/parse.y` and `src/ntp.c`. One of these definitions should be deleted.

The `ibuf_dns` variable is defined separately in `src/ntp.c` and `src/ntp_dns.c`. I'm not sure if these variables are meant to share storage or not. If they are, one of them should be made `extern` (or add an `extern` declaration to `src/ntp.h`). If they aren't, both should be made `static`.

**Comment by pbhenson** [comment]
Actually, I think the conf variable in parse.y should be renamed? It just gets assigned to the pointer passed in by the caller? I don't think they're meant to access the same variable.

**Comment by pbhenson** [comment]
Hmm, maybe not. This is confusing. In ntpd.c:

int
main(int argc, char *argv[])
        struct ntpd_conf         lconf;
[...]
        if (parse_config(conffile, &lconf))

Then in parse.c:

int
parse_config(const char *filename, struct ntpd_conf *xconf)
[...]
        p_conf = xconf;

Then in ntp.c:

struct ntpd_conf        *conf;
[...]
ntp_main(struct ntpd_conf *nconf, struct passwd *pw, int argc, char **argv)
[...]
        conf = nconf;

And back in ntpd.c:
              ntp_main(&lconf, pw, argc0, argv0);

So ntpd.c defines lconf, then passes a pointer to it to parse_config in parse.c which reads a bunch of stuff into it. That use is purely local to parse.c?

Then it calls ntp_main and ntp_dns passing them a pointer to it as well, ntp_dns.c declares it as a parameter named nconf that's local to the ntp_dns function. ntp.c declares one called conf at the global level, which is then set to the pointer passed in to ntp_main.

It doesn't seem any of them need to be global? They all end up as local pointers to the lconf variable from ntpd.c...

**Comment by michaelforney** [comment]
Yeah, I'm not completely sure either.

I ended up sending a patch for this to the mailing list, and it was applied:
https://marc.info/?l=openbsd-tech&m=158659156805753&w=2

If you think there is a better alternative fix, it's probably best to start a discussion there.

**Comment by pbhenson** [comment]
Cool, thanks for the pointer to the patch. It still seems a bit confusing the way the config gets passed around, but if it works and openbsd is happy with it's probably not worth worrying about :).

**Comment by ffontaine** [comment]
Could you import https://github.com/openntpd-portable/openntpd-openbsd/commit/956b4239d919d6922b9ba6ef39be0d1753f8ff34 to openntpd-portable? This patch is needed to fix a build failure with gcc 10 and does not apply cleanly on the latest official release (6.2p3).
