### ISSUE TITLE
Timestamps after 2030, NTP rollover in 2036

### ISSUE THREAD

**Issue by nsmoooose** [openntpd-portable/openntpd-portable#58]
In client.c openntpd will reject all timestamps beyond the year 2030 as bogus.

I think it is time to begin the work to fix the 2030 limit and the 2036 NTP rollover.
The things we build today will be used for several years to come.

Any plans on fixing this?

/Henrik

**Comment by reyk** [comment]
Funnily enough, it's 2020 now. OpenBSD has 64 time_t on all platforms for some years now so I'm wondering where this is coming from.

```c
	/*
	 * XXX workaround: time_t / tv_sec must never wrap.
	 * around 2020 we will need a solution (64bit time_t / tv_sec).
	 * consider every answer with a timestamp beyond january 2030 bogus.
	 */
	if (T2 > JAN_2030 || T3 > JAN_2030) {
		set_next(p, error_interval());
		return (0);
	}
```

**Comment by nsmoooose** [comment]
Closing this since this has been resolved.

Reference:
https://github.com/openntpd-portable/openntpd-openbsd/commit/0e2d6221804d407a32ba6c050dc8df416672d9f1#diff-17e83c22d737d6163a7e120abff17b21dd9683cff50dd2aae857cba9b00f5f5f
