### ISSUE TITLE
keep syncing but never set clock as sync

### ISSUE THREAD

**Issue by PingHao** [openntpd-portable/openntpd-portable#62]
Installed master version of this on my centos 7 box, ran it shows clock sync never happened, even the offset is quite small. Note that the only NTP server it refer to is a internal NTP server, which quite small latency, and chronyd have no issue to sync it and mark clock as synced. 

https://github.com/openntpd-portable/openntpd-portable/blob/cc3292981b83f7d691e96dc5e5a5d30af6f98454/patches/0014-use-adjtimex-over-adjtime-check-return-value-and-adj.patch#L59

I added a debug line in ntpd.c to see if the 
	} else if (!firstadj && tx.offset == offset) {
		synced = 1;
	}
	_**log_debug("offset %d -> %d", offset, tx.offset);**_
cause it. this is result:

reply from ntpserver: offset -0.000025 delay 0.000172, next query 31s
adjusting local clock by -0.000017s
offset -17 -> 0
reply from ntpserver: offset -0.000005 delay 0.000225, next query 32s
reply from ntpserver: offset -0.000024 delay 0.000182, next query 31s
reply from ntpserver: offset -0.000028 delay 0.000175, next query 34s
reply from ntpserver: offset -0.000031 delay 0.000165, next query 32s
reply from ntpserver: offset -0.000043 delay 0.000170, next query 30s
reply from ntpserver: offset -0.000035 delay 0.000204, next query 34s
adjusting local clock by -0.000031s
offset -30 -> 0
reply from ntpserver: offset -0.000006 delay 0.000228, next query 32s
reply from ntpserver: offset -0.000029 delay 0.000179, next query 34s
reply from ntpserver: offset -0.000039 delay 0.000165, next query 33s
reply from ntpserver: offset -0.000043 delay 0.000177, next query 31s
reply from ntpserver: offset -0.000047 delay 0.000181, next query 30s
reply from ntpserver: offset -0.000036 delay 0.000199, next query 30s
adjusting local clock by -0.000039s
offset -38 -> 0
reply from ntpserver: offset -0.000023 delay 0.000165, next query 30s

wander if it suppose to set synced = 1 if offset change to 0?

**Comment by busterb** [comment]
That seems reasonable to me.

**Comment by busterb** [comment]
I pushed a change to master after some local testing here, so far it seems to sync as expected. Would you mind giving it a try? Thanks.

**Comment by busterb** [comment]
I released 6.8p1 with this fix. Thanks for the help!
