### ISSUE TITLE
why libtls 3.2.2 requirement for latest release?

### ISSUE THREAD

**Issue by CameronNemo** [openntpd-portable/openntpd-portable#66]
The release notes state the following:

>To build OpenNTPD with time constraint support, libtls from LibreSSL 3.2.2 or later is recommended

At Void Linux we are not ready to upgrade from 3.1.5 and thus are building and testing with that version (https://github.com/void-linux/void-packages/pull/27053). Is there anything we should be concerned about?

**Comment by busterb** [comment]
I just made the update to the latest stable version since that's the version it shipped with in OpenBSD. But I do not believe there are any API incompatibilities with LibreSSL 3.1.5 either, if you would like to remain with that version.

**Comment by CameronNemo** [comment]
Thanks for the info.
