### ISSUE TITLE
linux: use adjtimex(2)

### ISSUE THREAD

**Issue by leahneukirchen** [openntpd-portable/openntpd-portable#7]
AFAIU, ntp_adjtime is an old alias for the adjtimex(2) syscall
(see https://sourceware.org/git/?p=glibc.git;a=commit;h=fc4157daf55dc41131e71c6149fbdc4099cb9b57)

Thus, compat/adjfreq_linux.c should use adjtimex directly.  This will allow building openntpd on musl libc.

**Comment by bcook-r7** [comment]
Thank you, that makes sense.

**Comment by busterb** [comment]
Fixed in eeb97529cd5a332a69a312687e41939eb17f7a81, thank you.
