### ISSUE TITLE
linux/musl: __BEGIN_DECLS

### ISSUE THREAD

**Issue by leahneukirchen** [openntpd-portable/openntpd-portable#8]
The final change required to build openntpd out of the box on linux/musl is removal of __BEGIN_DECLS/__END_DECLS.  I'm not sure what the best approach is.  We could either
remove these lines with a patch, or add a default definition somewhere...

**Comment by bcook-r7** [comment]
We probably don't need them, since these are private headers and we're not building for C++. IIRC they are not defined for HP-UX either.

**Comment by busterb** [comment]
This should be fixed now.
